image: php:7.4-fpm

definitions:
  steps:
    - step: &composer-install
        name: Build PHP
        caches:
          - composer
        script:
          - ls -al
          - apt-get update && apt-get install -qy unzip git curl libmcrypt-dev
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer --version
          - composer install --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader --prefer-dist --ignore-platform-reqs
        artifacts:
          - vendor/**

    - step: &deploy
        name: Deploy
        deployment: Test
        caches:
          - composer
        script:
          - apt-get update && apt-get install -qy unzip git curl libmcrypt-dev rsync gettext-base
          - envsubst < .env.pipelines.deploy > .env
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer --version
          - composer global require "laravel/envoy"
          - ~/.composer/vendor/bin/envoy run deploy --host=$DEPLOY_HOST --user=$DEPLOY_USER --path=$DEPLOY_PATH --build=$BITBUCKET_BUILD_NUMBER --commit=$BITBUCKET_COMMIT --branch=$BITBUCKET_BRANCH --php=php --dir=$BITBUCKET_CLONE_DIR

pipelines:
  default:
    - step: *composer-install

  branches:
    master:
      - step: *composer-install
      - parallel:
          - step:
              <<: *deploy
              deployment: Production
              name: Deploy to Production
          - step:
              <<: *deploy
              deployment: Sandbox
              name: Deploy to Sandbox

    dev:
      - step: *composer-install
      - step: *deploy
